zzyfilepath: C:/zzypdf/ 

server:
  port: 8021
spring:
  application:
    name: zzypdf
  redis:
    host: localhost
    database: 0
    port: 6379
    jedis:
      pool:
        max-active: 3
        max-wait: -1
        max-idle: 8
        min-idle: 0 
  resources:
    static-locations:
    - file:${zzyfilepath}
  mvc:
    static-path-pattern: /**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true   #访问路径显示为IP
zzyurl: 192.168.0.121:8888/pdf   