server:
  port: 7001
spring:
  application:
    name: servicecenter
eureka:
  instance:
    hostname: 192.168.0.69  #可以设置DNS名
    appname: servicecenter
  client:
    register-with-eureka: false  #单机版 false 表示不向服务中心注册自己
    fetch-registry: false  #单机版 false 表示自己就是注册中心，不需要去检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #defaultZone: http://192.168.0.69: 7001/eureka/, http://192.168.0.9:7001/eureka/  