server:
  port: 5000
spring:
  application:
    name: zzyusercenter
  datasource:
    url: jdbc:mysql://zzymysql.cwromzxlmahw.us-east-1.rds.amazonaws.com/usercenter 
    username: root
    password: Ns5R3IbQMdJopyQdM5kM5g==
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: zzyredis1.zb918y.ng.0001.use1.cache.amazonaws.com
    database: 0
    port: 6379
    jedis:
      pool:
        max-active: 3
        max-wait: -1
        max-idle: 8
        min-idle: 0
feign:
  hystrix:
    enabled: true  

super: Ns5R3IbQMdLLCeMRmd5OskUSp+GNeCa864oP6p0fSVfLj4hdhmtluD0NQI/X1DgPD8jR1vMGt/jgUTj2EzWHH9Kx9Pww+XN3w/pt4oS8oDc=
superu: http://192.168.0.121:8085/super.html