server:
  port: 8002
spring:
  application:
    name: zzymail
  mail:
    host: smtp.gmail.com
    port: 587
    username: kuzcosys@gmail.com
    password: gwhwdkhth
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    
  redis:
    host: localhost
    database: 0
    port: 6379
    jedis:
      pool:
        max-active: 3
        max-wait: -1
        max-idle: 8
        min-idle: 0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.69:7001/eureka/
  instance:
    instance-id: zzymail
    prefer-ip-address: true   #访问路径显示为IP

mailfrom: linuszhong@hotmail.com
zzymsgexchange: zzyboot-mail-exchange
zzymsgkey: zzyboot-mail-key