server:
  port: 3434
spring:
  application:
    name: configcenter
  cloud:
    config:
      server:
        git:
          uri: https://github.com/linuszhonggithub/zzyroot.git
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/ #http://zbservicecenter-env.utp7746uxp.us-east-1.elasticbeanstalk.com/eureka/
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true   #访问路径显示为IP